/**
 * Eligible-channel spotlight — EVENT-triggered broadcast (distinct from the
 * time-triggered mining pulse). Fires when a channel newly passes the
 * content-gen bar, with a rich per-channel post: stats + top video titles +
 * top thumbnails + a live channel-page screenshot (best-effort).
 *
 * Freshness: a high-water mark (broadcast_spotlight_since, stamped on first
 * run) means we only post channels DISCOVERED after the feature turned on —
 * never the historical backlog of already-eligible channels. Each channel is
 * posted at most once (broadcast_posts.featured_key = 'chan:<id>'). Bounded
 * per tick so a post-backfill surge drains steadily instead of flooding.
 */
import type { Pool } from 'pg';
import { fmt } from './report';
import { esc, sendTelegramSpotlight, type SendResult } from './senders';

export interface ChannelPostConfig { token: string; chat: string }
interface SpotlightConfig extends ChannelPostConfig { since: string | null; perTick: number }

async function loadConfig(pool: Pool): Promise<SpotlightConfig> {
  const r = await pool.query<{ key: string; value: string }>(
    `SELECT key, value FROM admin_config WHERE key IN
       ('broadcast_telegram_token','broadcast_telegram_chat','broadcast_spotlight_since','broadcast_spotlight_per_tick')`,
  );
  const c: Record<string, string> = {};
  for (const row of r.rows) c[row.key] = row.value;
  return {
    token: c.broadcast_telegram_token || '',
    chat: c.broadcast_telegram_chat || '',
    since: c.broadcast_spotlight_since || null,
    perTick: parseInt(c.broadcast_spotlight_per_tick) || 1,
  };
}

/**
 * SQL predicate excluding YouTube's AUTO-GENERATED channels from public posts.
 * "<Artist> - Topic" channels (1,250+ in the corpus) are machine-created music
 * containers, not real creators — they can cross a growth threshold on a label
 * upload and would be an embarrassing thing to broadcast as a "discovery".
 * Applied to every post type; `c` must alias niche_spy_channels.
 */
export const NOT_AUTOGEN_SQL = `
  COALESCE(c.channel_name, '') NOT LIKE '% - Topic'
  AND COALESCE(c.channel_name, '') <> 'Various Artists'
  AND COALESCE(c.channel_name, '') NOT LIKE 'Release - %'`;

/** Runtime guard for the single-channel send paths (test endpoint, ticks). */
export function isAutoGenerated(name: string | null): boolean {
  const n = (name ?? '').trim();
  return /\s-\sTopic$/.test(n) || n === 'Various Artists' || /^Release - /.test(n);
}

export interface ChannelRow { channel_id: string; channel_name: string | null; subscriber_count: number | null; channel_created_at: Date | null; video_count: number | null }
export interface VideoRow { title: string | null; thumbnail: string | null; view_count: number | null; url: string | null; posted_at: Date | null }

export interface GatheredChannel {
  ch: ChannelRow;
  vids: VideoRow[];
  format: string;
  durations: Map<string, number>;   // ytId -> seconds (drives badges + format)
  firstPostedAt: Date | null;       // earliest upload we've seen — "started posting" age
}

/**
 * Fetch a channel + its top videos, then resolve real video durations via one
 * proxied videos.list call. Durations give BOTH the YouTube-style duration
 * badges and the shorts/long-form label — our stored is_short column is only
 * ~4% filled, so the old ratio-based label was usually silently absent.
 */
export async function gatherChannel(pool: Pool, channelId: string): Promise<GatheredChannel | null> {
  const chRes = await pool.query<ChannelRow>(
    `SELECT channel_id, channel_name, subscriber_count, channel_created_at, video_count
       FROM niche_spy_channels WHERE channel_id = $1`, [channelId],
  );
  if (!chRes.rows[0]) return null;
  // Pull a few extra so the duration sample (and thus the format label) is
  // meaningful even when some rows lack a usable id.
  const vidsRes = await pool.query<VideoRow>(
    `SELECT title, thumbnail, view_count, url, posted_at FROM niche_spy_videos
      WHERE channel_id = $1 AND thumbnail IS NOT NULL
      ORDER BY view_count DESC NULLS LAST LIMIT 8`, [channelId],
  );
  const { extractYtId, fetchDurations, formatLabelFromDurations } = await import('./cards');
  const ids = vidsRes.rows.map(v => extractYtId(v.url)).filter((x): x is string => !!x);
  const durations = await fetchDurations(ids);
  const format = formatLabelFromDurations([...durations.values()]);
  // Earliest upload across ALL the channel's videos (not just the thumbnailed 8)
  // — this is the "started posting" age, which is the meaningful signal for a
  // channel that's blowing up now. channel_created_at is the ACCOUNT age and is
  // often misleading (an old account that only recently started posting).
  const fp = await pool.query<{ first: Date | null }>(
    `SELECT MIN(posted_at) first FROM niche_spy_videos WHERE channel_id = $1 AND posted_at IS NOT NULL`, [channelId]);
  const firstPostedAt = fp.rows[0]?.first ?? null;
  // Return the full pool (up to 8) — sendRichChannelPost composes cards
  // sequentially and keeps the first 4 that render, so dead thumbnails on the
  // top videos fall through to the next ones instead of emptying the post.
  return { ch: chRes.rows[0], vids: vidsRes.rows, format, durations, firstPostedAt };
}

/** Shared rich sender: screenshot (best-effort) + thumbnails + caption, logged
 *  to broadcast_posts with the given kind + dedup key. Used by both spotlight
 *  and growth-story events. */
export async function sendRichChannelPost(
  pool: Pool, cfg: ChannelPostConfig, channelId: string,
  caption: string, vids: VideoRow[], dedupKey: string | null, kind: string,
  durations?: Map<string, number>,
): Promise<SendResult> {
  const { composeVideoCard, extractYtId, heroCrop } = await import('./cards');
  const t0 = Date.now();

  // HERO first: the channel-grid screenshot, cropped wide so Telegram gives it
  // its own full-width row (the raw portrait capture rendered as a small tile).
  const images: Buffer[] = [];
  const tShot = Date.now();
  const shot = await captureChannelShot(channelId);
  const shotMs = Date.now() - tShot;
  if (shot) images.push(await heroCrop(shot));

  // Then YouTube-style cards. Compose SEQUENTIALLY, not in parallel: i.ytimg.com
  // rate-limits a 4-wide burst to all-404, and each thumbnail needs a resolution
  // fallback walk (maxresdefault, the stored URL, often 404s). Draw from the full
  // video pool and keep the first 4 that actually render, so videos with dead or
  // restricted thumbnails don't leave gaps (or an empty post).
  const tCards = Date.now();
  let cardsAttempted = 0;
  for (const v of vids) {
    if (images.length - (shot ? 1 : 0) >= 4) break;   // 4 cards is enough
    cardsAttempted++;
    const ytId = extractYtId(v.url);
    const card = await composeVideoCard(
      { ytId, thumbnail: v.thumbnail, title: v.title, viewCount: v.view_count, postedAt: v.posted_at },
      ytId ? durations?.get(ytId) ?? null : null,
    ).catch(() => null);
    if (card) images.push(card);
  }
  const cardsMs = Date.now() - tCards;
  const cardsBuilt = images.length - (shot ? 1 : 0);

  // NEVER publish a bare text-only channel post — that's below the quality bar.
  // If neither the hero nor any card rendered, skip the send: log a non-ok
  // 'no_images' row (featured_key NULL, so a growth channel's cooldown is NOT
  // burned and it's retried on a later tick once thumbnails/capture recover),
  // and return not-ok so the caller's tick moves on to the next candidate.
  if (images.length === 0) {
    const meta = {
      shot_ok: false, shot_ms: shotMs, cards_attempted: cardsAttempted, cards_built: 0,
      cards_ms: cardsMs, durations_resolved: durations ? durations.size : 0,
      images_sent: 0, via: null, skipped: 'no_images', degraded: true, total_ms: Date.now() - t0,
    };
    await pool.query(
      `INSERT INTO broadcast_posts (kind, featured_key, ok, targets, payload, error, channel_id, meta)
       VALUES ($1, NULL, false, 'telegram', $2, 'no_images', $3, $4::jsonb)`,
      [kind, caption.slice(0, 4000), channelId, JSON.stringify(meta)],
    ).catch(() => {});
    console.warn(`[${kind}] chan=${channelId} SKIPPED no_images (hero+${cardsAttempted} cards all failed) ${meta.total_ms}ms`);
    return { target: 'telegram', ok: false, error: 'no_images_skipped' };
  }

  const res = await sendTelegramSpotlight(cfg.token, cfg.chat, caption, images);

  // Diagnostics for later post-mortems — every degradation is visible here
  // (no screenshot? cards dropped? durations unresolved? fell back to text?).
  const meta = {
    shot_ok: !!shot,
    shot_ms: shotMs,
    cards_attempted: cardsAttempted,
    cards_built: cardsBuilt,
    cards_ms: cardsMs,
    durations_resolved: durations ? durations.size : 0,
    images_sent: images.length,
    bytes: images.reduce((a, b) => a + b.length, 0),
    via: res.via ?? null,
    message_ids: res.messageIds ?? [],   // enables deleteMessage on a bad post
    degraded: res.via === 'text' || !shot,
    total_ms: Date.now() - t0,
  };
  await pool.query(
    `INSERT INTO broadcast_posts (kind, featured_key, ok, targets, payload, error, channel_id, meta)
     VALUES ($1, $2, $3, 'telegram', $4, $5, $6, $7::jsonb)`,
    [kind, dedupKey, res.ok, caption.slice(0, 4000), res.ok ? null : res.error ?? null, channelId, JSON.stringify(meta)],
  ).catch(err => console.error(`[${kind}] post log failed:`, (err as Error).message));
  console.log(`[${kind}] chan=${channelId} via=${res.via} shot=${shot ? 'yes' : 'NO'} cards=${cardsBuilt}/${cardsAttempted} durs=${meta.durations_resolved} ${meta.total_ms}ms -> ${res.ok ? 'ok' : 'FAIL:' + res.error}`);
  return res;
}

/** "3 days ago" / "~2 months ago" / "~19 years ago" — a relative age from now. */
export function agoText(d: Date | null): string {
  if (!d) return '';
  const days = Math.max(0, Math.round((Date.now() - new Date(d).getTime()) / 86_400_000));
  if (days === 0) return 'today';
  if (days === 1) return '1 day ago';
  if (days < 45) return `${days} days ago`;
  const months = Math.round(days / 30);
  if (months < 18) return `~${months} months ago`;
  const years = days / 365;
  return `~${years.toFixed(years >= 10 ? 0 : 1).replace(/\.0$/, '')} years ago`;
}

/** "🌱 started posting ~2 months ago" from the earliest upload, or '' if unknown. */
export function startedPostingLine(firstPostedAt: Date | null): string {
  const a = agoText(firstPostedAt);
  return a ? `🌱 started posting ${a}` : '';
}

/** Account-creation line — labeled explicitly so it's not confused with the
 *  "started posting" age (an old account can start posting recently). */
export function accountCreatedLine(created: Date | null): string {
  const a = agoText(created);
  return a ? `📅 account created ${a}` : '';
}

export function buildSpotlightCaption(ch: ChannelRow, vids: VideoRow[], format = '', firstPostedAt: Date | null = null): string {
  const name = ch.channel_name ?? ch.channel_id;
  const url = `https://www.youtube.com/channel/${ch.channel_id}`;
  const lines: string[] = [];
  lines.push(`🎯 <b>NEW CHANNEL ON OUR RADAR</b>`);
  lines.push('');
  lines.push(`<a href="${esc(url)}"><b>${esc(name)}</b></a>`);
  if (format) lines.push(format);
  const bits: string[] = [];
  if (ch.subscriber_count != null) bits.push(`👥 ${fmt(ch.subscriber_count)} subscribers`);
  if (ch.video_count != null) bits.push(`🎬 ${fmt(ch.video_count)} videos`);
  if (bits.length) lines.push(bits.join('  ·  '));
  const posting = startedPostingLine(firstPostedAt);
  if (posting) lines.push(posting);
  const created = accountCreatedLine(ch.channel_created_at);
  if (created) lines.push(created);
  if (vids.length) {
    lines.push('');
    lines.push(`<b>Popular uploads:</b>`);
    for (const v of vids.slice(0, 4)) {
      const t = (v.title ?? '').slice(0, 70);
      const vv = v.view_count != null ? ` — ${fmt(v.view_count)} views` : '';
      lines.push(`• ${esc(t)}${vv}`);
    }
  }
  // Telegram media-caption hard limit is 1024 chars.
  return lines.join('\n').slice(0, 1024);
}

/** Best-effort channel-page screenshot → PNG bytes, or null on any failure. */
async function captureChannelShot(channelId: string): Promise<Buffer | null> {
  try {
    const [{ captureYtScreen }, fs] = await Promise.all([
      import('@/lib/content-gen/yt-capture'),
      import('fs/promises'),
    ]);
    // 25s cap: a warm cache returns in <1s; a cold capture needs multiple proxy
    // attempts and usually can't finish in time anyway, so a long timeout just
    // delays the post. The video cards carry the images; the grid is a bonus.
    const res = await Promise.race([
      captureYtScreen(channelId, { kind: 'videos_tab_popular', mode: 'static' }),
      new Promise<never>((_, rej) => setTimeout(() => rej(new Error('capture timeout')), 25_000)),
    ]);
    const p = (res as { local_path?: string })?.local_path;
    if (!p) return null;
    const buf = await fs.readFile(p);
    return buf.length > 1000 ? buf : null;
  } catch (err) {
    console.warn(`[spotlight] screenshot skipped for ${channelId}: ${(err as Error).message}`);
    return null;
  }
}

/**
 * Compose + send one spotlight for a specific channel. `dedupKey` is stamped
 * on the broadcast_posts row (pass 'chan:<id>' for real posts so the channel
 * never repeats; pass null for test sends so they don't suppress the real one).
 */
export async function sendSpotlightFor(
  pool: Pool, cfg: SpotlightConfig, channelId: string, dedupKey: string | null,
): Promise<SendResult> {
  const g = await gatherChannel(pool, channelId);
  if (!g) return { target: 'telegram', ok: false, error: 'channel not found' };
  if (isAutoGenerated(g.ch.channel_name)) return { target: 'telegram', ok: false, error: 'auto-generated channel (skipped)' };
  const caption = buildSpotlightCaption(g.ch, g.vids, g.format, g.firstPostedAt);
  return sendRichChannelPost(pool, cfg, channelId, caption, g.vids, dedupKey, 'eligible_spotlight', g.durations);
}

export interface SpotlightTickResult { ran: boolean; reason?: string; sent: number }

/** Event tick — posts newly-eligible, un-broadcast channels (oldest first). */
export async function runEligibleSpotlightTick(): Promise<SpotlightTickResult> {
  const pool = await getPoolLocal();
  const cfg = await loadConfig(pool);
  if (!cfg.token || !cfg.chat) return { ran: false, reason: 'no_telegram', sent: 0 };

  // First run: stamp the high-water mark and post nothing (skip the backlog).
  if (!cfg.since) {
    await pool.query(
      `INSERT INTO admin_config (key, value) VALUES ('broadcast_spotlight_since', NOW()::text)
         ON CONFLICT (key) DO UPDATE SET value = NOW()::text`,
    ).catch(() => {});
    return { ran: true, reason: 'high_water_mark_set', sent: 0 };
  }

  const todo = await pool.query<{ channel_id: string }>(
    `SELECT s.channel_id
       FROM channel_cg_status s
       JOIN niche_spy_channels c ON c.channel_id = s.channel_id
      WHERE s.cg_eligible = true
        AND s.discovered_at > $1::timestamptz
        AND ${NOT_AUTOGEN_SQL}
        AND NOT EXISTS (SELECT 1 FROM broadcast_posts b WHERE b.featured_key = 'chan:'||s.channel_id)
      ORDER BY s.cg_evaluated_at ASC
      LIMIT $2`,
    // Over-fetch fallbacks: a channel with no usable images returns not-ok and
    // is skipped, so we need extras to still land perTick real posts.
    [cfg.since, cfg.perTick + 4],
  );
  if (todo.rows.length === 0) return { ran: true, sent: 0 };

  let sent = 0;
  for (const row of todo.rows) {
    if (sent >= cfg.perTick) break;
    const res = await sendSpotlightFor(pool, cfg, row.channel_id, `chan:${row.channel_id}`);
    if (res.ok) sent++;   // not-ok (no_images skip) → try the next eligible channel
  }
  return { ran: true, sent };
}

// Lazy pool import to keep this module's import graph small.
async function getPoolLocal(): Promise<Pool> {
  const { getPool } = await import('@/lib/db');
  return getPool();
}
